name: build
on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build
        run: ./gradlew build -x test

      - name: Code format
        uses: axel-op/googlejavaformat-action@v4
        with:
          args: '--replace'
          commit-message: "chore: format"

      - name: Version bump
        shell: python
        # I DONT CARE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        run: |
          with open('build.gradle', 'r') as file:
              data = file.readlines()

          curr_version = data[7][11:-2].split('.')
          curr_version[1] = str(int(curr_version[1]) + 1)
          bump_version = 'version = \'' + '.'.join(curr_version) + '\'\n'
          data[7] = bump_version
          
          with open('build.gradle', 'w') as file:
              file.writelines(data)

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: bump version"
